### ISSUE TITLE
Scrubbing international format phone numbers

### ISSUE THREAD

**Issue by hashwin** [ankane/logstop#14]
The current phone regex does not match international format like "+14129996294".
Maybe this regex could be added as a separate option:
```
/^\+(?:[0-9] ?){6,14}[0-9]$/
```

**Comment by ankane** [comment]
Hey @hashwin, thanks for the suggestion! Added support for scrubbing [E.164](https://en.wikipedia.org/wiki/E.164) numbers in the commit above.
