### ISSUE TITLE
`URL_PASSWORD_REGEX` Is matching on values outside of a URL

### ISSUE THREAD

**Issue by afolta** [ankane/logstop#16]
Hi, 

The [URL_PASSWORD_REGEX](https://github.com/ankane/logstop/blob/5101df1ee0179fe6f7c0970d324dc5fa5be1e130/lib/logstop.rb#L16)  appears to be overly greedy and is matching on values that fall outside of the URL, causing `user` values to be unnecessarily filtered. See the below test string and the match that is causing the log to return a filtered user as:
`{\"foo\":\"app_name\",\"bar\":\"./file.rb\",\"level\":\"error\",\"error\":\"HTTP POST request to: http://localhost:3000//url/50000091/call\",\"request-id\":\"e6ce7cb8-054d-415c-a194-45d5df583648\",\"user\":\"[FILTERED]@oreilly.test\",\"time\":\"2023-06-30T14:25:43Z\"}`

**Test String:**
`{\"foo\":\"app_name\",\"bar\":\"./file.rb\",\"level\":\"error\",\"error\":\"HTTP POST request to: http://localhost:3000//url/50000091/call\",\"request-id\":\"e6ce7cb8-054d-415c-a194-45d5df583648\",\"user\":\"joey.grady@oreilly.test\",\"time\":\"2023-06-30T14:25:43Z\"}`

**Match:**

`//localhost:3000//url/50000091/call\",\"request-id\":\"e6ce7cb8-054d-415c-a194-45d5df583648\",\"user\":\"joey.grady@`

<img width="1008" alt="Screen Shot 2023-06-30 at 12 52 27 PM" src="https://github.com/ankane/logstop/assets/53487342/88040485-880f-43f0-ae92-0131e3f08a54">

Would it be possible to update the Regex to be a bit less greedy for url_passwords?

**Comment by ankane** [comment]
Hi @afolta, thanks for reporting! Pushed a fix for this specific pattern in the commit above.

(also, I'd recommend not using emails as user identifiers in logs)

**Comment by afolta** [comment]
> Hi @afolta, thanks for reporting! Pushed a fix for this specific pattern in the commit above.
> 
> (also, I'd recommend not using emails as user identifiers in logs)

Thanks for the quick fix @ankane ! I tested out the new Regex in Rubular and am still seeing an overly inclusive match. Am I missing something here? 
![Screen Shot 2023-06-30 at 2 16 28 PM](https://github.com/ankane/logstop/assets/53487342/268e7c59-5136-49c7-a112-e577acb46b2b)

**Comment by ankane** [comment]
My bad, should be fixed now.

**Comment by afolta** [comment]
> My bad, should be fixed now.

Thanks a ton for this update! It's much appreciated.
