### ISSUE TITLE
Scrub Active Record query logs by attribute names

### ISSUE THREAD

**Issue by piotrwodz** [ankane/logstop#8]
### Feature request

Add an option of Active Record scrubbing. This would allow for filtering Active Record query logs by passing attribute names.

## Describe the solution

For the time being `logstop` scrubs Personal Identifiable Information (PII) based on default and custom regular expressions. This is cool! 🥇

However, when using this gem in Rails, I would like to have an option of providing a list of attributes (via config initializer) to be scrubbed from Active Record query logs.

**Comment by ankane** [comment]
Future readers: see #9 for discussion.
